# basic options
title: Test-Blog
author: Some Guy
email: your-email@domain.com
description: A wonderful site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
